name: "Bug report 🐛"
description: Report errors or unexpected behavior
title: "Bug Report: "
labels:
  - bug
  - backlog
assignees: "marvinbuss"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Before submitting, please make sure to [search through existing issues](https://github.com/Azure/data-product-streaming/issues) and [check the Known Issues section](/docs/EnterpriseScaleAnalytics-KnownIssues.md).

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Mode
      description: How was the deployment executed?
      multiple: false
      options:
        - Deploy To Azure
        - Azure DevOps
        - GitHub Actions
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Tell us the steps required to trigger your bug.
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: If possible, please share the error message that you received.
      placeholder: Error Messages
      render: json
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, please include screenshots and paste them into the markdown editor below.
      placeholder: Screenshots
    validations:
      required: false

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
